struct WebService {
    static let baseUrl                               = "https://baldevkrishan.com/ivalt_v1/public"
    static let privacyPolicy                         = "https://ivalt.com/privacypolicy-eula.html"
    static let FAQS                                  = "http://ivalt.com/faqs-for-iphone.php"
    static let help                                  = "https://www.ivalt.com/help/"
    static let register                              = "\(baseUrl)/webcard/register/mobile/user"
    static let registeredUserDetail                  = "\(baseUrl)/webcard/registered-user-details"
    static let sendSMS                               = "\(baseUrl)/wp/send/sms"
    static let registerConfirmation                  = "\(baseUrl)/wp/register/confirmation"
    static let loginConfirmation                     = "\(baseUrl)/wp/confirm-login-auth"
    static let updateToken                           = "\(baseUrl)/webcard/mobile/refresh/token"
    static let global                                = "\(baseUrl)/global/authenticate"
    static let deleteUser                            = "\(baseUrl)/webcard/remove-user"
}

struct WSRequestParams {
    static let WS_REQS_PARAM_MOBILE                  = "mobile"
    static let WS_REQS_PARAM_EMAIL                   = "email"
    static let WS_REQS_PARAM_USER_CODE               = "user_code"
    static let WS_REQS_PARAM_COUNTRY_CODE            = "country_code"
    static let WS_REQS_PARAM_DEVICE_TOKEN            = "device_token"
    static let WS_REQS_PARAM_PLATFORM                = "platform"
    static let WS_REQS_PARAM_TOKEN                   = "token"
    static let WS_REQS_PARAM_DOMAIN                  = "domain"
    static let WS_REQS_PARAM_NAME                    = "name"
    static let WS_REQS_PARAM_IMEI                    = "imei"
    static let WS_REQS_PARAM_LATITUDE                = "latitude"
    static let WS_REQS_PARAM_LONGITUDE               = "longitude"
    static let WS_REQS_PARAM_ADDRESS                 = "address"
    static let WS_REQS_PARAM_SUPPLIER_ID             = "supplier_id"
    static let WS_REQS_PARAM_SUPPLIER                = "supplier"
}

struct WSResponseParams {
    static let WS_RESP_PARAM_STATUS                  = "status"
    static let WS_RESP_PARAM_SUCCESS                 = "success"
    static let WS_RESP_PARAM_MESSAGE                 = "message"
    static let WS_RESP_PARAM_DATA                    = "data"
    static let WS_RESP_PARAM_DATE                    = "date"
    static let WS_RESP_PARAM_ERROR                   = "error"
    static let WS_RESP_PARAM_ID                      = "id"
    static let WS_RESP_PARAM_WEBSITES                = "websites"
    static let WS_RESP_PARAM_LOGS                    = "logs"
    static let WS_RESP_PARAM_DETAIL                  = "detail"
    static let WS_RESP_PARAM_CREATED_AT              = "created_at"
    static let WS_RESP_PARAM_IS_ENROLLED             = "is_enrolled"
    static let WS_RESP_PARAM_USER_DETAILS            = "userDetails"
}
